; Script generated by the HM NIS Edit Script Wizard.
SetCompressor /SOLID lzma
RequestExecutionLevel admin

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "Nikita"
!define PRODUCT_VERSION "${__DATE__}"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\Nikita\Nikita.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License Java page
!insertmacro MUI_PAGE_LICENSE "..\licenses\installer.java.license.rtf"
; License Solr page
!insertmacro MUI_PAGE_LICENSE "..\licenses\installer.solr.LICENSE.txt"
; License Solr page
;!insertmacro MUI_PAGE_LICENSE "installer.my.LICENSE.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$SYSDIR\sc.exe"
!define MUI_FINISHPAGE_RUN_PARAMETERS 'start journal2Ct'
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "Russian"

; MUI end ------
Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Nikita.setup.${__DATE__}.exe"
InstallDir $PROGRAMFILES64\Nikita
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  ;�� ������ ��� allusers!!!!
  SetShellVarContext all
  
  ExecWait '"$SYSDIR\sc.exe" stop Nikita'
  Sleep 2000
  ExecWait '"$SYSDIR\sc.exe" delete Nikita'
  Sleep 2000
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File ..\Nikita.epf
  File ..\Nikita.cfe
  File add.firewall.rule.cmd
  File /r ..\dist\Nikita\*.* 
  
  CreateDirectory   "$SMPROGRAMS\Nikita"
  ;CreateShortCut    "$SMPROGRAMS\Nikita\������������ ���������.lnk"     "$INSTDIR\pcnsl.exe"
  CreateShortCut    "$SMPROGRAMS\Nikita\������� ��������� ��.lnk"       "$INSTDIR\Nikita.epf"
  WriteINIStr       "$SMPROGRAMS\Nikita\������ ����������.url"          "InternetShortcut"  "URL"  "http://localhost:8984"

  !define           shortcut_install_svc        "$SMPROGRAMS\Nikita\���������� ������.lnk"
  CreateShortCut    "${shortcut_install_svc}"   "$INSTDIR\Nikita.exe"       "install"
  ShellLink::SetRunAsAdministrator              "${shortcut_install_svc}"

  !define           shortcut_run_svc            "$SMPROGRAMS\Nikita\��������� ������.lnk"
  CreateShortCut    "${shortcut_run_svc}"       "$SYSDIR\sc.exe"                "start journal2Ct"  "$INSTDIR\Journal2Ct.exe"
  ShellLink::SetRunAsAdministrator              "${shortcut_run_svc}"

  !define           shortcut_stop_svc           "$SMPROGRAMS\Nikita\���������� ������.lnk"
  CreateShortCut    "${shortcut_stop_svc}"      "$SYSDIR\sc.exe"                "stop journal2Ct"   "$INSTDIR\Journal2Ct.exe"
  ShellLink::SetRunAsAdministrator              "${shortcut_stop_svc}"

  !define           shortcut_del_svc            "$SMPROGRAMS\Nikita\������� ������.lnk"
  CreateShortCut    "${shortcut_del_svc}"       "$SYSDIR\sc.exe"                "delete journal2Ct" "$INSTDIR\Journal2Ct.exe"
  ShellLink::SetRunAsAdministrator              "${shortcut_del_svc}"

  !define           shortcut_run_console        "$SMPROGRAMS\Nikita\��������� � �������.lnk"
  CreateShortCut    "${shortcut_run_console}"   "$INSTDIR\Journal2Ct.exe"       "console"
  ShellLink::SetRunAsAdministrator              "${shortcut_run_console}"
SectionEnd

Section -AdditionalIcons
  ;�� ������ ��� allusers!!!!
  SetShellVarContext all

  CreateShortCut "$SMPROGRAMS\Nikita\�������.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\Journal2Ct.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\Journal2Ct.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  ExecWait '"$SYSDIR\cmd.exe" /c "$INSTDIR\add.firewall.rule.cmd"'
  ExecWait '"$INSTDIR\pcnsl.exe"'
  ExecWait '"$INSTDIR\Journal2Ct.exe" --startup auto install'
SectionEnd

Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "�������� ��������� $(^Name) ���� ������� ���������."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "�� ������� � ���, ��� ������� ������� $(^Name) � ��� ����������� ������� ���������?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  ;�� ������ ��� allusers!!!!
  SetShellVarContext all

  ExecWait '"$SYSDIR\sc.exe" stop Nikita'
  ExecWait '"$SYSDIR\sc.exe" delete Nikita'
  ExecWait '"$SYSDIR\netsh.exe" advfirewall firewall delete rule name="Nikita"'
  RMDir /r $INSTDIR
  Delete "$SMPROGRAMS\Nikita\*.*"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd